const MoroccanCities = [
  "Casablanca",
  "Rabat",
  "Fes",
  "Marrakech",
  "Tangier",
  "Agadir",
  "Meknes",
  "Oujda",
  "Kenitra",
  "Tetouan",
  "Safi",
  "El Jadida",
  "Nador",
  "Beni Mellal",
  "Khouribga",
  "Ksar El Kebir",
  "Taourirt",
  "Taza",
  "Settat",
  "Larache",
  "Guelmim",
  "Berrechid",
  "Ouarzazate",
  "Berkane",
  "Ouezzane",
  "Mohammedia",
  "Al Hoceima",
  "Khemisset",
  "Sidi Slimane",
  "Tiznit",
  "Inezgane",
  "Taroudant",
  "Fkih Ben Salah",
  "Temara",
  "Sefrou",
  "Sidi Kacem",
  "Midelt",
  "Azrou",
  "Errachidia",
  "Ksar El Kebir",
  "Sidi Bennour",
  "Taounate",
  "Tata",
  "Tissa",
  "Imouzzer Du Kandar",
  "Outabouabane",
  "Moulay Bousselham",
  "Ifrane",
];

export default MoroccanCities;
